#!/usr/bin/env python
# dcomp
# Compares source_directory and destination_directory
# Author: N.Manago Nov,11,2014
# $Revision: 93 $
# $Date: 2016-10-03 20:24:21 +0900 (Mon, 03 Oct 2016) $
import os
import sys
import re
import shutil
import filecmp
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
from argparse import ArgumentParser,RawTextHelpFormatter

# Default values
SRCDIR = '.'

# Read options
parser = ArgumentParser(usage='%(prog)s destination_directory [options]',formatter_class=lambda prog:RawTextHelpFormatter(prog,max_help_position=200,width=200))
parser.add_argument('-s','--srcdir',default=SRCDIR,help='Set source_directory (%(default)s)')
parser.add_argument('--dstdir',default=None,help='Set destination_directory (%(default)s)')
parser.add_argument('-d','--move_different',default=False,action='store_true',help='Move different files to destination_directory (%(default)s)')
parser.add_argument('-D','--copy_different',default=False,action='store_true',help='Copy different files to destination_directory (%(default)s)')
parser.add_argument('-m','--move_missing',default=False,action='store_true',help='Move missing files to destination_directory (%(default)s)')
parser.add_argument('-M','--copy_missing',default=False,action='store_true',help='Copy missing files to destination_directory (%(default)s)')
parser.add_argument('-r','--remove_same',default=False,action='store_true',help='Remove same files in source_directory (%(default)s)')
parser.add_argument('-S','--size_only',default=False,action='store_true',help='Check size only (%(default)s)')
parser.add_argument('-n','--dry_run',default=False,action='store_true',help='Perform a trial run with no changes made (%(default)s)')
parser.add_argument('-q','--quiet',default=False,action='store_true',help='Quiet mode (%(default)s)')
(args,rest) = parser.parse_known_args()
if args.dstdir is None:
    if len(rest) != 1:
        parser.print_help()
        sys.exit(-1)
    else:
        args.dstdir = rest[0]
if not os.path.isdir(args.dstdir):
    raise IOError('No such directory >>> '+args.dstdir)
else:
    args.dstdir = args.dstdir.rstrip(os.path.sep) # to remove trailing '/'
if not os.path.isdir(args.srcdir):
    raise IOError('No such directory >>> '+args.srcdir)
else:
    args.srcdir = args.srcdir.rstrip(os.path.sep) # to remove trailing '/'
srcdir = os.path.abspath(args.srcdir)
dstdir = os.path.abspath(args.dstdir)

def is_subdir(path,directory):
    path = os.path.realpath(path)
    directory = os.path.realpath(directory)
    try:
        relative = os.path.relpath(path,directory)
    except Exception:
        relative = ''
    return not relative.startswith(os.pardir)

def move_file(src,dst,quiet=False):
    if os.path.exists(dst):
        if quiet:
            os.remove(dst)
            shutil.move(src,dst)
        else:
            sys.stderr.write(f'Overwrite {dst}?\n')
            line = sys.stdin.readline()
            if re.search('[yY]',line):
                os.remove(dst)
                shutil.move(src,dst)
    else:
        shutil.move(src,dst)

def copy_file(src,dst,quiet=False,directory=False):
    if os.path.exists(dst):
        if quiet:
            if os.path.isdir(src):
                if not directory:
                    raise IOError(f'Error, {src} is a directory.')
                os.removedirs(dst)
                shutil.copytree(src,dst,symlinks=True)
            else:
                os.remove(dst)
                if os.path.islink(src):
                    linkto = os.readlink(src)
                    os.symlink(linkto,dst)
                else:
                    shutil.copy2(src,dst)
        else:
            sys.stderr.write(f'Overwrite {dst}?\n')
            line = sys.stdin.readline()
            if re.search('[yY]',line):
                if os.path.isdir(src):
                    if not directory:
                        raise IOError(f'Error, {src} is a directory.')
                    os.removedirs(dst)
                    shutil.copytree(src,dst,symlinks=True)
                else:
                    os.remove(dst)
                    if os.path.islink(src):
                        linkto = os.readlink(src)
                        os.symlink(linkto,dst)
                    else:
                        shutil.copy2(src,dst)
    else:
        if os.path.isdir(src):
            if not directory:
                raise IOError(f'Error, {src} is a directory.')
            shutil.copytree(src,dst,symlinks=True)
        else:
            if os.path.islink(src):
                linkto = os.readlink(src)
                os.symlink(linkto,dst)
            else:
                shutil.copy2(src,dst)

def remove_file(src,quiet=False):
    if quiet:
        os.remove(src)
    else:
        sys.stderr.write(f'Remove {src}?\n')
        line = sys.stdin.readline()
        if re.search('[yY]',line):
            os.remove(src)

if is_subdir(srcdir,dstdir):
    raise ValueError('Error, srcdir is inside dstdir.')
if is_subdir(dstdir,srcdir):
    raise ValueError('Error, dstdir is inside srcdir.')

nsam = 0
nmis = 0
ndif = 0
old_stdout = sys.stdout
sys.stdout = mystdout = StringIO()
filecmp.dircmp(args.srcdir,args.dstdir,ignore=[]).report_full_closure()
sys.stdout = old_stdout
lines = mystdout.getvalue().splitlines()
dirs = []
copy_list = []
move_list = []
remove_list = []
for line in lines:
    if not re.search(r'\S',line):
        srcdir = None
        dstdir = None
        continue
    m = re.search(rf'diff\s+{args.srcdir}(.*)\s+{args.dstdir}\1$',line)
    if m:
        srcdir = args.srcdir+m.group(1)
        dstdir = args.dstdir+m.group(1)
        continue
    if '(' in srcdir or ')' in srcdir:
        m = re.search(u'Only\s+in\s+%s\s*:\s*(\[.*\])'%(srcdir.replace('(','\(').replace(')','\)')),line)
    else:
        m = re.search(u'Only\s+in\s+%s\s*:\s*(\[.*\])'%(srcdir),line)
    if m:
        files = eval(m.group(1))
        for f in files:
            fnam = os.path.join(srcdir,f)
            gnam = os.path.join(dstdir,f)
            sys.stderr.write('M %s\n'%(gnam))
            if args.copy_missing:
                if os.path.exists(gnam):
                    raise IOError(f'Error, already exists {gnam}')
                else:
                    copy_list.append((fnam,gnam,True))
            elif args.move_missing:
                if os.path.exists(gnam):
                    raise IOError(f'Error, already exists {gnam}')
                else:
                    move_list.append((fnam,gnam))
            nmis += 1
        continue
    if '(' in dstdir or ')' in dstdir:
        m = re.search(u'Only\s+in\s+%s'%(dstdir.replace('(','\(').replace(')','\)')),line)
    else:
        m = re.search(u'Only\s+in\s+%s'%(dstdir),line)
    if m: # Do nothing
        continue
    m = re.search(r'Identical\s+files\s*:\s*(\[.*\])',line)
    if m:
        files = eval(m.group(1))
        for f in files:
            fnam = os.path.join(srcdir,f)
            gnam = os.path.join(dstdir,f)
            if os.path.islink(fnam):
                if os.path.islink(gnam):
                    test = (os.readlink(fnam) == os.readlink(gnam))
                else:
                    test = False
            elif os.path.islink(gnam):
                test = False
            elif args.size_only:
                test = (os.path.getsize(fnam) == os.path.getsize(gnam))
            else:
                test = filecmp.cmp(fnam,gnam,shallow=False)
            if not test:
                sys.stderr.write(f'D {fnam} {gnam}\n')
                if args.copy_different:
                    copy_list.append((fnam,gnam,False))
                elif args.move_different:
                    move_list.append((fnam,gnam))
                ndif += 1
            else:
                if os.path.realpath(fnam) == os.path.realpath(gnam):
                    if not args.quiet:
                        sys.stderr.write(f'SI {fnam}\n')
                else:
                    if os.path.dirname(os.path.realpath(fnam)) != os.path.abspath(os.path.dirname(fnam)): # inside a link
                        if not args.quiet:
                            sys.stderr.write(f'SL {fnam}\n')
                    else:
                        if not args.quiet:
                            sys.stderr.write(f'S {fnam}\n')
                        if args.remove_same:
                            remove_list.append(fnam)
                nsam += 1
        continue
    m = re.search(r'Differing\s+files\s*:\s*(\[.*\])',line)
    if m:
        files = eval(m.group(1))
        for f in files:
            fnam = os.path.join(srcdir,f)
            gnam = os.path.join(dstdir,f)
            sys.stderr.write(f'D {fnam} {gnam}\n')
            if args.copy_different:
                copy_list.append((fnam,gnam,False))
            elif args.move_different:
                move_list.append((fnam,gnam))
            ndif += 1
        continue
    m = re.search(r'Common\s+subdirectories\s*:\s*(\[.*\])',line)
    if m:
        subs = [os.path.join(srcdir,d) for d in eval(m.group(1))]
        dirs.extend(subs)
        continue
    m = re.search(r'Common\s+funny\s+cases\s*:\s*(\[.*\])',line)
    if m:
        files = eval(m.group(1))
        for f in files:
            fnam = os.path.join(srcdir,f)
            gnam = os.path.join(dstdir,f)
            if os.path.islink(fnam):
                if os.path.islink(gnam):
                    test = (os.readlink(fnam) == os.readlink(gnam))
                else:
                    test = False
            elif os.path.islink(gnam):
                test = False
            elif args.size_only:
                test = (os.path.getsize(fnam) == os.path.getsize(gnam))
            else:
                test = filecmp.cmp(fnam,gnam,shallow=False)
            if not test:
                sys.stderr.write(f'D {fnam} {gnam}\n')
                if args.copy_different:
                    copy_list.append((fnam,gnam,False))
                elif args.move_different:
                    move_list.append((fnam,gnam))
                ndif += 1
            else:
                if os.path.realpath(fnam) == os.path.realpath(gnam):
                    if not args.quiet:
                        sys.stderr.write(f'SI {fnam}\n')
                else:
                    if os.path.dirname(os.path.realpath(fnam)) != os.path.abspath(os.path.dirname(fnam)): # inside a link
                        if not args.quiet:
                            sys.stderr.write(f'SL {fnam}\n')
                    else:
                        if not args.quiet:
                            sys.stderr.write(f'S {fnam}\n')
                        if args.remove_same:
                            remove_list.append(fnam)
                nsam += 1
        continue
    sys.stderr.write(f'Unprocessed line in ({srcdir} {dstdir}):\n')
    sys.stderr.write(line+'\n')
ncop = 0
nmov = 0
nrem = 0
for fnam,gnam,flag in copy_list:
    if args.dry_run:
        sys.stderr.write(f'cp {fnam} {gnam}\n')
    else:
        copy_file(fnam,gnam,args.quiet,directory=flag)
        if os.path.exists(gnam):
            ncop += 1
for fnam,gnam in move_list:
    if args.dry_run:
        sys.stderr.write(f'mv {fnam} {gnam}\n')
    else:
        move_file(fnam,gnam,args.quiet)
        if not os.path.exists(fnam) and os.path.exists(gnam):
            nmov += 1
for fnam in remove_list:
    if args.dry_run:
        sys.stderr.write(f'rm {fnam}\n')
    else:
        remove_file(fnam,args.quiet)
        if not os.path.exists(fnam):
            nrem += 1
if args.remove_same:
    for d in dirs:
        if args.dry_run:
            sys.stderr.write(f'rmdir {d}\n')
        else:
            try:
                if args.quiet:
                    os.removedirs(d)
                else:
                    sys.stderr.write(f'Remove {d}?\n')
                    line = sys.stdin.readline()
                    if re.search('[yY]',line):
                        os.removedirs(d)
            except Exception:
                pass
sys.stderr.write(f'Same    : {nsam:5d} files\n')
sys.stderr.write(f'Missing : {nmis:5d} files\n')
sys.stderr.write(f'Differ  : {ndif:5d} files\n')
sys.stderr.write(f'Moved   : {nmov:5d} files\n')
sys.stderr.write(f'Copied  : {ncop:5d} files\n')
sys.stderr.write(f'Removed : {nrem:5d} files\n')
